# -*- coding: utf-8 -*-
"""
Точка входа для работы с api.exchangerate.host.
Используется ботом для конвертации и проверки валют.
"""

from api_client import get_config, convert, get_currencies_list, check_currencies_available

# Маппинг: страна (название, по-русски или по-английски) -> код валюты (ISO 4217)
# Пользователь вводит страну — бот подставляет валюту и проверяет через API.
COUNTRY_TO_CURRENCY = {
    # Россия и СНГ
    "россия": "RUB",
    "russia": "RUB",
    "рф": "RUB",
    "казахстан": "KZT",
    "kazakhstan": "KZT",
    "беларусь": "BYN",
    "belarus": "BYN",
    "украина": "UAH",
    "ukraine": "UAH",
    "армения": "AMD",
    "armenia": "AMD",
    "азербайджан": "AZN",
    "azerbaijan": "AZN",
    "грузия": "GEL",
    "georgia": "GEL",
    "киргизия": "KGS",
    "киргистан": "KGS",
    "kyrgyzstan": "KGS",
    "таджикистан": "TJS",
    "tajikistan": "TJS",
    "туркменистан": "TMT",
    "turkmenistan": "TMT",
    "узбекистан": "UZS",
    "uzbekistan": "UZS",
    "молдова": "MDL",
    "moldova": "MDL",
    "молдавия": "MDL",
    # США и Америка
    "сша": "USD",
    "usa": "USD",
    "америка": "USD",
    "united states": "USD",
    "канада": "CAD",
    "canada": "CAD",
    "мексика": "MXN",
    "mexico": "MXN",
    "куба": "CUP",
    "cuba": "CUP",
    "ямайка": "JMD",
    "jamaica": "JMD",
    "гаити": "HTG",
    "haiti": "HTG",
    "доминикана": "DOP",
    "dominican republic": "DOP",
    "доминиканская республика": "DOP",
    "пуэрто-рико": "USD",
    "puerto rico": "USD",
    "багамы": "BSD",
    "bahamas": "BSD",
    "барбадос": "BBD",
    "barbados": "BBD",
    "тринидад и тобаго": "TTD",
    "trinidad and tobago": "TTD",
    "тринидад": "TTD",
    "гватемала": "GTQ",
    "guatemala": "GTQ",
    "гондурас": "HNL",
    "honduras": "HNL",
    "никарагуа": "NIO",
    "nicaragua": "NIO",
    "коста-рика": "CRC",
    "costa rica": "CRC",
    "панама": "PAB",
    "panama": "PAB",
    "белиз": "BZD",
    "belize": "BZD",
    "сальвадор": "USD",
    "el salvador": "USD",
    # Южная Америка
    "бразилия": "BRL",
    "brazil": "BRL",
    "аргентина": "ARS",
    "argentina": "ARS",
    "чили": "CLP",
    "chile": "CLP",
    "колумбия": "COP",
    "colombia": "COP",
    "перу": "PEN",
    "peru": "PEN",
    "венесуэла": "VES",
    "venezuela": "VES",
    "эквадор": "USD",
    "ecuador": "USD",
    "боливия": "BOB",
    "bolivia": "BOB",
    "парагвай": "PYG",
    "paraguay": "PYG",
    "уругвай": "UYU",
    "uruguay": "UYU",
    "гайана": "GYD",
    "guyana": "GYD",
    "суринам": "SRD",
    "suriname": "SRD",
    # Европа (EUR)
    "европа": "EUR",
    "евросоюз": "EUR",
    "еврозона": "EUR",
    "eurozone": "EUR",
    "германия": "EUR",
    "germany": "EUR",
    "франция": "EUR",
    "france": "EUR",
    "италия": "EUR",
    "italy": "EUR",
    "испания": "EUR",
    "spain": "EUR",
    "греция": "EUR",
    "greece": "EUR",
    "португалия": "EUR",
    "portugal": "EUR",
    "нидерланды": "EUR",
    "netherlands": "EUR",
    "голландия": "EUR",
    "бельгия": "EUR",
    "belgium": "EUR",
    "австрия": "EUR",
    "austria": "EUR",
    "ирландия": "EUR",
    "ireland": "EUR",
    "финляндия": "EUR",
    "finland": "EUR",
    "словакия": "EUR",
    "slovakia": "EUR",
    "словения": "EUR",
    "slovenia": "EUR",
    "эстония": "EUR",
    "estonia": "EUR",
    "латвия": "EUR",
    "latvia": "EUR",
    "литва": "EUR",
    "lithuania": "EUR",
    "кипр": "EUR",
    "cyprus": "EUR",
    "мальта": "EUR",
    "malta": "EUR",
    "люксембург": "EUR",
    "luxembourg": "EUR",
    "хорватия": "EUR",
    "croatia": "EUR",
    # Европа (не EUR)
    "великобритания": "GBP",
    "great britain": "GBP",
    "англия": "GBP",
    "uk": "GBP",
    "united kingdom": "GBP",
    "британия": "GBP",
    "швейцария": "CHF",
    "switzerland": "CHF",
    "польша": "PLN",
    "poland": "PLN",
    "чехия": "CZK",
    "czech": "CZK",
    "czech republic": "CZK",
    "венгрия": "HUF",
    "hungary": "HUF",
    "румыния": "RON",
    "romania": "RON",
    "болгария": "BGN",
    "bulgaria": "BGN",
    "българия": "BGN",
    "сербия": "RSD",
    "serbia": "RSD",
    "черногория": "EUR",
    "montenegro": "EUR",
    "северная македония": "MKD",
    "macedonia": "MKD",
    "македония": "MKD",
    "албания": "ALL",
    "albania": "ALL",
    "босния": "BAM",
    "bosnia": "BAM",
    "босния и герцеговина": "BAM",
    "bosnia and herzegovina": "BAM",
    "исландия": "ISK",
    "iceland": "ISK",
    "норвегия": "NOK",
    "norway": "NOK",
    "швеция": "SEK",
    "sweden": "SEK",
    "дания": "DKK",
    "denmark": "DKK",
    "андорра": "EUR",
    "andorra": "EUR",
    "монако": "EUR",
    "monaco": "EUR",
    "сан-марино": "EUR",
    "san marino": "EUR",
    "ватикан": "EUR",
    "vatican": "EUR",
    # Турция и Кавказ
    "турция": "TRY",
    "turkey": "TRY",
    # Азия
    "китай": "CNY",
    "china": "CNY",
    "япония": "JPY",
    "japan": "JPY",
    "южная корея": "KRW",
    "south korea": "KRW",
    "корея": "KRW",
    "korea": "KRW",
    "северная корея": "KPW",
    "north korea": "KPW",
    "монголия": "MNT",
    "mongolia": "MNT",
    "тайвань": "TWD",
    "taiwan": "TWD",
    "гонконг": "HKD",
    "hong kong": "HKD",
    "макао": "MOP",
    "macau": "MOP",
    "индия": "INR",
    "india": "INR",
    "пакистан": "PKR",
    "pakistan": "PKR",
    "бангладеш": "BDT",
    "bangladesh": "BDT",
    "шри-ланка": "LKR",
    "sri lanka": "LKR",
    "непал": "NPR",
    "nepal": "NPR",
    "бутан": "BTN",
    "bhutan": "BTN",
    "мальдивы": "MVR",
    "maldives": "MVR",
    "афганистан": "AFN",
    "afghanistan": "AFN",
    "индонезия": "IDR",
    "indonesia": "IDR",
    "малайзия": "MYR",
    "malaysia": "MYR",
    "сингапур": "SGD",
    "singapore": "SGD",
    "таиланд": "THB",
    "thailand": "THB",
    "вьетнам": "VND",
    "vietnam": "VND",
    "камбоджа": "KHR",
    "cambodia": "KHR",
    "лаос": "LAK",
    "laos": "LAK",
    "мьянма": "MMK",
    "myanmar": "MMK",
    "бирма": "MMK",
    "филиппины": "PHP",
    "philippines": "PHP",
    "бруней": "BND",
    "brunei": "BND",
    "восточный тимор": "USD",
    "east timor": "USD",
    "тимор": "USD",
    # Ближний Восток
    "оаэ": "AED",
    "uae": "AED",
    "дубай": "AED",
    "dubai": "AED",
    "united arab emirates": "AED",
    "саудовская аравия": "SAR",
    "saudi arabia": "SAR",
    "саудия": "SAR",
    "израиль": "ILS",
    "israel": "ILS",
    "иран": "IRR",
    "iran": "IRR",
    "ирак": "IQD",
    "iraq": "IQD",
    "кувейт": "KWD",
    "kuwait": "KWD",
    "бахрейн": "BHD",
    "bahrain": "BHD",
    "катар": "QAR",
    "qatar": "QAR",
    "оман": "OMR",
    "oman": "OMR",
    "йемен": "YER",
    "yemen": "YER",
    "иордания": "JOD",
    "jordan": "JOD",
    "ливан": "LBP",
    "lebanon": "LBP",
    "сирия": "SYP",
    "syria": "SYP",
    "палестина": "ILS",
    "palestine": "ILS",
    # Африка
    "египет": "EGP",
    "egypt": "EGP",
    "юар": "ZAR",
    "south africa": "ZAR",
    "южная африка": "ZAR",
    "нигерия": "NGN",
    "nigeria": "NGN",
    "кения": "KES",
    "kenya": "KES",
    "танзания": "TZS",
    "tanzania": "TZS",
    "уганда": "UGX",
    "uganda": "UGX",
    "эфиопия": "ETB",
    "ethiopia": "ETB",
    "гана": "GHS",
    "ghana": "GHS",
    "марокко": "MAD",
    "morocco": "MAD",
    "тунис": "TND",
    "tunisia": "TND",
    "алжир": "DZD",
    "algeria": "DZD",
    "ливия": "LYD",
    "libya": "LYD",
    "судан": "SDG",
    "sudan": "SDG",
    "сенегал": "XOF",
    "senegal": "XOF",
    "кот-д'ивуар": "XOF",
    "ivory coast": "XOF",
    "камерун": "XAF",
    "cameroon": "XAF",
    "замбия": "ZMW",
    "zambia": "ZMW",
    "зимбабве": "ZWL",
    "zimbabwe": "ZWL",
    "маврикий": "MUR",
    "mauritius": "MUR",
    "ботсвана": "BWP",
    "botswana": "BWP",
    "намибия": "NAD",
    "namibia": "NAD",
    "мозамбик": "MZN",
    "mozambique": "MZN",
    "ангола": "AOA",
    "angola": "AOA",
    "руанда": "RWF",
    "rwanda": "RWF",
    "мадагаскар": "MGA",
    "madagascar": "MGA",
    "малави": "MWK",
    "malawi": "MWK",
    "др конго": "CDF",
    "drc": "CDF",
    "конго": "CDF",
    "congo": "CDF",
    "габон": "XAF",
    "gabon": "XAF",
    "бенин": "XOF",
    "benin": "XOF",
    "мали": "XOF",
    "mali": "XOF",
    "нигер": "XOF",
    "niger": "XOF",
    "буркина-фасо": "XOF",
    "burkina faso": "XOF",
    "того": "XOF",
    "togo": "XOF",
    "гвинея": "GNF",
    "guinea": "GNF",
    "сомали": "SOS",
    "somalia": "SOS",
    "либерия": "LRD",
    "liberia": "LRD",
    "мавритания": "MRU",
    "mauritania": "MRU",
    "гамбия": "GMD",
    "gambia": "GMD",
    "сейшелы": "SCR",
    "seychelles": "SCR",
    "кабо-верде": "CVE",
    "cape verde": "CVE",
    "эсватини": "SZL",
    "eswatini": "SZL",
    "свазиленд": "SZL",
    "swaziland": "SZL",
    "лесото": "LSL",
    "lesotho": "LSL",
    # Океания
    "австралия": "AUD",
    "australia": "AUD",
    "новая зеландия": "NZD",
    "new zealand": "NZD",
    "папуа — новая гвинея": "PGK",
    "papua new guinea": "PGK",
    "папуа": "PGK",
    "фиджи": "FJD",
    "fiji": "FJD",
    "самоа": "WST",
    "samoa": "WST",
    "тонга": "TOP",
    "tonga": "TOP",
    "вануату": "VUV",
    "vanuatu": "VUV",
    "соломоновы острова": "SBD",
    "solomon islands": "SBD",
    "кирибати": "AUD",
    "kiribati": "AUD",
    "микронезия": "USD",
    "micronesia": "USD",
    "маршалловы острова": "USD",
    "marshall islands": "USD",
    "палау": "USD",
    "palau": "USD",
}


def country_to_currency(country: str) -> str | None:
    """Возвращает код валюты по названию страны или None, если не найдено."""
    if not country or not isinstance(country, str):
        return None
    key = country.strip().lower()
    return COUNTRY_TO_CURRENCY.get(key)


def get_rate_and_convert(access_key: str, from_cur: str, to_cur: str, amount: float):
    """Конвертация через API. Возвращает результат convert()."""
    return convert(access_key, from_cur, to_cur, amount)
